### ISSUE TITLE
Read binary with struct

### ISSUE THREAD

**Issue by tytannial** [dschu012/D2SLib#1]
`public static class BinaryReaderExt
{
    public static T ReadStruct<T>(this BinaryReader reader)
    {
        byte[] bytes = reader.ReadBytes(Marshal.SizeOf(typeof(T)));

        GCHandle handle = GCHandle.Alloc(bytes, GCHandleType.Pinned);
        T theStructure = (T)Marshal.PtrToStructure(handle.AddrOfPinnedObject(), typeof(T));
        handle.Free();

        return theStructure;
    }
}`

It will fill the struct with binary.

**Comment by dschu012** [comment]
Once you get to the skills section of the binary the data is no longer byte aligned. To my knowledge that'd only work for fields that are byte aligned.

**Comment by tytannial** [comment]
> Once you get to the skills section of the binary the data is no longer byte aligned. To my knowledge that'd only work for fields that are byte aligned.
You're right. https://github.com/dotnet/csharplang/discussions/465
But I will take time for bit base layouts and find a solution. 😀

**Comment by dschu012** [comment]
Also the size in bits for each stat is variable. For example if you look at https://github.com/dschu012/D2SLib/blob/master/src/Resources/Itemstatcost.txt the Csv bits column controls how many bits the stat is. So strength is 10 bits while hp and mana are 21. Then the stats on item are similar (variable bit size) but looking at the at different columns in that txt.
